/**
 * Import email templates from the monday.com Communications docs folder
 * (Volunteer Communications Templates) into the Email Templates board.
 *
 * Usage:
 *   npm run import:communications-docs
 *   npm run import:communications-docs -- --dry-run
 */

import dotenv from 'dotenv';
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  blocksToPlainText,
  generalizeDocPlaceholders,
  slugFromDocName,
  type MondayDocBlock,
} from '../src/utils/mondayDocBlocks.ts';
import {
  api,
  createMondayClient,
  createTemplateItem,
  ensureColumn,
  ensureEmailTemplatesBoard,
  fetchBoardColumns,
  fetchExistingTemplates,
  updateTemplateItem,
  upsertEnvBoardId,
  type SeedTemplate,
} from './lib/emailTemplatesBoard.ts';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = resolve(__dirname, '..');
const envPath = resolve(projectRoot, '.env');
const outputPath = resolve(projectRoot, 'src/data/communicationsDocs.imported.ts');

dotenv.config({ path: envPath });

const FOLDER_NAME =
  process.env.VITE_COMMUNICATIONS_DOCS_FOLDER_NAME ||
  'Volunteer Communications Templates';

const dryRun = process.argv.includes('--dry-run');
const replaceExisting = process.argv.includes('--replace');

interface FolderChild {
  id: string;
  name: string;
}

interface MondayDocSummary {
  id: string;
  name: string;
  object_id: string;
  url?: string | null;
  blocks: MondayDocBlock[];
}

export interface ImportedCommunicationsTemplate extends SeedTemplate {
  mondayDocId: string;
  mondayDocObjectId: string;
  mondayDocUrl?: string;
}

function folderMatches(name: string, target: string): boolean {
  const normalized = name.trim().toLowerCase();
  const needle = target.trim().toLowerCase();
  return normalized === needle || normalized.includes(needle);
}

async function findCommunicationsFolder(
  monday: ReturnType<typeof createMondayClient>,
): Promise<{ id: string; name: string; children: FolderChild[] }> {
  const data = await api<{
    folders: Array<{ id: string; name: string; children: FolderChild[] }>;
  }>(monday, `query { folders { id name children { id name } } }`);

  const folder =
    data.folders.find((entry) => folderMatches(entry.name, FOLDER_NAME)) ??
    data.folders.find((entry) => folderMatches(entry.name, 'communications'));

  if (!folder) {
    throw new Error(
      `Could not find a docs folder matching "${FOLDER_NAME}". Set VITE_COMMUNICATIONS_DOCS_FOLDER_NAME in .env.`,
    );
  }

  return folder;
}

async function fetchDocsByObjectIds(
  monday: ReturnType<typeof createMondayClient>,
  objectIds: string[],
): Promise<Map<string, MondayDocSummary>> {
  const listed = await api<{
    docs: Array<{ id: string; name: string; object_id: string; url?: string | null }>;
  }>(monday, `query { docs(limit: 500) { id name object_id url } }`);

  const docsByObjectId = new Map<string, MondayDocSummary>();
  const objectIdSet = new Set(objectIds);

  for (const doc of listed.docs) {
    if (!objectIdSet.has(doc.object_id)) continue;

    const detail = await api<{ docs: MondayDocSummary[] }>(
      monday,
      `query ($ids: [ID!]) {
        docs(ids: $ids) {
          id
          name
          object_id
          url
          blocks { type content }
        }
      }`,
      { ids: [doc.id] },
    );

    const full = detail.docs[0];
    if (!full) continue;
    docsByObjectId.set(full.object_id, full);
  }

  return docsByObjectId;
}

export function docToEmailTemplate(doc: MondayDocSummary): ImportedCommunicationsTemplate {
  const slug = slugFromDocName(doc.name);
  const body = generalizeDocPlaceholders(blocksToPlainText(doc.blocks));

  return {
    id: `comms-${slug}`,
    name: doc.name.trim(),
    subject: doc.name.trim(),
    body,
    mondayDocId: doc.id,
    mondayDocObjectId: doc.object_id,
    mondayDocUrl: doc.url ?? undefined,
  };
}

function writeImportedModule(templates: ImportedCommunicationsTemplate[]): void {
  if (dryRun) {
    console.log(`Would write ${templates.length} template(s) to ${outputPath}`);
    return;
  }

  const body = `/** Generated by \`npm run import:communications-docs\`. Do not edit by hand. */

export const COMMUNICATIONS_IMPORTED_TEMPLATES = ${JSON.stringify(templates, null, 2)} as const;
`;

  writeFileSync(outputPath, body, 'utf8');
  console.log(`Wrote ${outputPath}`);
}

async function main(): Promise<void> {
  if (!process.env.MONDAY_API_TOKEN) {
    console.error('MONDAY_API_TOKEN is required in .env');
    process.exit(1);
  }

  const monday = createMondayClient();
  const folder = await findCommunicationsFolder(monday);
  console.log(`Using folder "${folder.name}" (${folder.id}) — ${folder.children.length} doc(s)`);

  if (folder.children.length === 0) {
    console.log('No docs in folder.');
    return;
  }

  const docsByObjectId = await fetchDocsByObjectIds(
    monday,
    folder.children.map((child) => child.id),
  );

  const templates: ImportedCommunicationsTemplate[] = [];
  for (const child of folder.children) {
    const doc = docsByObjectId.get(child.id);
    if (!doc) {
      console.warn(`Skip missing doc for "${child.name}" (${child.id})`);
      continue;
    }
    templates.push(docToEmailTemplate(doc));
  }

  if (templates.length === 0) {
    throw new Error('No communications docs could be loaded.');
  }

  writeImportedModule(templates);

  const boardId = await ensureEmailTemplatesBoard(monday, dryRun);
  await ensureColumn(monday, boardId, 'Subject', 'text', dryRun);
  await ensureColumn(monday, boardId, 'Body', 'long_text', dryRun);
  await ensureColumn(monday, boardId, 'Template ID', 'text', dryRun);

  const columns =
    boardId === 'dry-run-board-id' ? [] : await fetchBoardColumns(monday, boardId);
  const existingByTemplateId =
    boardId === 'dry-run-board-id'
      ? new Map<string, string>()
      : await fetchExistingTemplates(monday, boardId);

  let created = 0;
  let updated = 0;
  for (const template of templates) {
    const existingItemId = existingByTemplateId.get(template.id);
    if (existingItemId) {
      if (replaceExisting) {
        await updateTemplateItem(
          monday,
          boardId,
          existingItemId,
          columns,
          template,
          dryRun,
        );
        updated += 1;
      } else {
        console.log(`Skip existing ${template.id}`);
      }
      continue;
    }
    await createTemplateItem(monday, boardId, columns, template, dryRun);
    created += 1;
  }

  upsertEnvBoardId(envPath, boardId, dryRun);
  console.log(
    `Done. ${created} template(s) imported, ${updated} updated from Communications docs.`,
  );
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
